# NOTE(mabay): This was generated by claude and not used at all. This is merely here for reference purposes.

import matplotlib.pyplot as plt
import numpy as np
import time

plt.ion()  # interactive mode ON

fig, ax = plt.subplots()
points, = ax.plot([], [], 'bo')  # empty scatter/line, updated each frame
ax.set_xlim(0, 10)
ax.set_ylim(0, 10)

x = np.random.uniform(0, 10, size=4)
y = np.random.uniform(0, 10, size=4)

try:
    while plt.fignum_exists(fig.number):  # loop ends if window is closed
        # --- update step ---
        x += np.random.uniform(-0.2, 0.2, size=4)
        y += np.random.uniform(-0.2, 0.2, size=4)

        # --- render step ---
        points.set_data(x, y)
        fig.canvas.draw_idle()
        fig.canvas.flush_events()

        time.sleep(0.1)

except KeyboardInterrupt:
    pass